name: reVC Linux AMD64

on:
  push:
    branches: [ vc ]
  pull_request:
    branches: [ vc ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libopenal-dev libglew-dev libglfw3-dev libsndfile1-dev libmpg123-dev build-essential

      - name: Make premake5Linux executable
        run: chmod +x ./premake5Linux

      - name: Run premake5
        run: ./premake5Linux --with-librw gmake2 --no-git-hash

      - name: Build debug project
        run: |
          cd build
          make config=debug_linux-amd64-librw_gl3_glfw-oal -j$(nproc)

      - name: Package debug build output
        run: |
          cd build/bin
          tar czvf ../../reVC-linux-amd64-debug.tar.gz *

      - name: Build release project
        run: |
          cd build
          make config=release_linux-amd64-librw_gl3_glfw-oal -j$(nproc)

      - name: Package release build output
        run: |
          cd build/bin
          tar czvf ../../reVC-linux-amd64-release.tar.gz *

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v4
        with:
          name: reVC-linux-amd64-debug
          path: reVC-linux-amd64-debug.tar.gz

      - name: Upload release build artifact
        uses: actions/upload-artifact@v4
        with:
          name: reVC-linux-amd64-release
          path: reVC-linux-amd64-release.tar.gz
